# For testing
version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.0.0
    ports:
      - 9200:9200
      - 9600:9600
    expose:
      - 9200
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
  superset:
    build: ./superset
    ports:
      - 8088:8088
    expose:
      - 8088
